#██╗░░░██╗░█████╗░██╗░░░██╗  ██████╗░██╗░░░░░██╗░░░██╗░██████╗░██╗███╗░░██╗
#╚██╗░██╔╝██╔══██╗██║░░░██║  ██╔══██╗██║░░░░░██║░░░██║██╔════╝░██║████╗░██║
#░╚████╔╝░██║░░██║██║░░░██║  ██████╔╝██║░░░░░██║░░░██║██║░░██╗░██║██╔██╗██║
#░░╚██╔╝░░██║░░██║██║░░░██║  ██╔═══╝░██║░░░░░██║░░░██║██║░░╚██╗██║██║╚████║
#░░░██║░░░╚█████╔╝╚██████╔╝  ██║░░░░░███████╗╚██████╔╝╚██████╔╝██║██║░╚███║
#░░░╚═╝░░░░╚════╝░░╚═════╝░  ╚═╝░░░░░╚══════╝░╚═════╝░░╚═════╝░╚═╝╚═╝░░╚══╝
#
#          here you can edit the configuration of your plugin

messages:
  no-permission: "&b[HSecurity] &8&l» &cYou do not have permissions to run this command."
  no-args: "&b[HSecurity] &8&l» &cwrong command try with /help"